#ifndef MSIPCHEADER
#define MSIPCHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved.
// See .../src/LICENSE for terms of distribution
//
//
///////////////////////////////////////////////////////////////////////////////

#include <MSIPC/MSChannel.H>
#include <MSIPC/MSConnection.H>
#include <MSIPC/MSListener.H>
#include <MSIPC/MSProtocol.H>
#include <MSIPC/MSTimer.H>

#endif
