language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

compiler:
  - clang
  - gcc

os:
  - linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cp ./lib/* ./bin/
  - ./bin/aplus ../tests/fsftest.+

