#ifndef AGIFHEADER
#define AGIFHEADER

///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1997-2008 Morgan Stanley All rights reserved.
// See .../src/LICENSE for terms of distribution.
//
//
///////////////////////////////////////////////////////////////////////////////

#include <AplusGUI/AplusDisplayServer.H>
#include <MSGUI/MSColorManager.H>
#include <a/fncdcls.h>

#endif // AGIFHEADER
